### ISSUE TITLE
请问这个编辑器如何清除图片排版格式？

### ISSUE THREAD

**Issue by dazhigarret** [TyrantG/dcat-admin-braft-editor#1]
![f8ad0bcedb4193ca8203fbc5c7759ce](https://user-images.githubusercontent.com/37061087/119151547-15d92800-ba82-11eb-812e-d5e09f300ccc.png)
图片中间隔了这个缝隙太丑了🤣🤣

**Comment by TyrantG** [comment]
不好意思，这么多天没回复。
可以参考一下作者的建议 [#256](https://github.com/margox/braft-editor/issues/256)

**Comment by dazhigarret** [comment]
好的，谢谢
